spring:
  datasource:
    url: jdbc:h2:mem:shortdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  jpa: # checks on what to do with tables and entities
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shortener}
    username: ${DB_USER:shortener}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate